#!/bin/bash

######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $TARGET
#  $PYTHONPATH


target="$1"

# 1. rebuild the drawwaretoolrifier ("compiler") every time...
das2json ${drawwaretool}.drawio
python main.py "${CALLERPATH}/${target}".drawio main ${target}.drawio.json | splitoutputs
checkfailure
mv out.py "${CALLERPATH}/${target}.py"

# # if you only want to use the T2T tool, then comment out the above and use the following:
# output=/dev/stdout
# ./pbp/t2t "${target}" </dev/null >$output


############################



