#!/bin/bash

######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $PYTHONPATH
#  $TARGET

# 1. rebuild the drawwaretoolrifier ("compiler") every time...
das2json ${TARGET}.drawio
python main.py "${CALLERPATH}/${TARGET}".drawio main ${TARGET}.drawio.json | splitoutputs
checkfailure
mv out.py "${CALLERPATH}/${TARGET}.py"

# # if you only want to use the T2T tool, then comment out the above and use the following:
# output=/dev/stdout
# ./pbp/t2t "${TARGET}" </dev/null >$output


############################



