#!/bin/bash

echo "@makec empty"

# ######### commands specific to this project #############
# # env vars that may be used in this script:
# #  $PATH
# #  $TOOLWD ($(pwd))
# #  $CALLERPATH
# #  $TARGET
# #  $PYTHONPATH

## modify the below manually to customize for your project...

# node ./pbp/das/das2json.mjs <drawing>.drawio
# rm -f out.md
# python main.py '<arg>' <top-most tab name> <drawing>.drawio.json

# ############################



