#!/bin/bash
set -e
# npm install
node das2json.mjs kernel.drawio

for i in $BASENAMES; do
    ./tas.bash "$i"
done

: > new_kernel0d.py
: > new_kernel0d.js
: > new_kernel0d.lisp

for i in $BASENAMES; do
    cat "$i.py" >> new_kernel0d.py
    cat "$i.js" >> new_kernel0d.js
    cat "$i.lisp" >> new_kernel0d.lisp
done
