#!/bin/bash
set -e
# npm install
node das2json.mjs kernel.drawio

for i in $BASENAMES; do
    ./tas.bash "$i"
done

: > new_kernel0d.py
: > new_kernel0d.js
: > new_kernel0d.c

for i in $BASENAMES; do
    cat "_python/$i.py" >> new_kernel0d.py
    cat "_js/$i.js" >> new_kernel0d.js
    cat "_lisp/$i.lisp" >> new_kernel0d.lisp
    cat "_c/$i.c" >> new_kernel0d.c
done

rm -f out.*
