#!/bin/bash
set -e
npm install
node das2json.mjs kernel.drawio
./regression_tas.bash 'jit'
./regression_tas.bash 'stock'
./regression_tas.bash '0d'
cat 0d.py jit.py stock.py >regression2_kernel0d.py

if diff -q regression_kernel0d.py regression2_kernel0d.py > /dev/null; then
    echo "OK, created: _$(date +%Y%m%d_%H%M%S)_kernel0d.py"
    cp kernel0d.py "_$(date +%Y%m%d_%H%M%S)_kernel0d.py"
    mv regression2_kernel0d.py kernel0d.py
else
    echo "Regression error: regression_kernel0d.py and regression2_kernel0d.py differ"
    diff regression_kernel0d.py regression2_kernel0d.py
fi

