#!/bin/bash
set -e
# npm install
node das2json.mjs kernel.drawio

for i in $BASENAMES; do
    ./regression_test_tas.bash "$i"
done

: > _r_python/rtkernel0d.py
: > _r_js/rtkernel0d.js
: > _r_lisp/rtkernel0d.lisp
: > _r_c/rtkernel0d.c

for i in $NTYLIST; do
    cat "_python/$i.py" >> _r_python/rtkernel0d.py
    cat "_js/$i.js" >> _r_js/rtkernel0d.js
    cat "_lisp/$i.lisp" >> _r_lisp/rtkernel0d.lisp
done

for i in $TYLIST; do
    cat "_c/$i.c" >> _r_c/rtkernel0d.c
done

exit 1

if diff -q new_kernel0d.py _r_python/rtkernel0d.py > /dev/null; then
    echo "OK, created: _backup/_$(date +%Y%m%d_%H%M%S)_kernel0d.py"
    cp kernel0d.py "_backup/_$(date +%Y%m%d_%H%M%S)_kernel0d.py"
    mv new_kernel0d.py kernel0d.py
    mv new_kernel0d.js kernel0d.js
    mv new_kernel0d.lisp kernel0d.lisp
    mv new_kernel0d.c kernel0d.c
else
    echo "Regression error: new_kernel0d.py and regression_test/rtkernel0d.py differ"
    echo "use diff new_kernel0d.py regression_test/rtkernel0d.py"
fi

rm -f out.*
