decl("causingMevent",id3).
decl("child",id4).
decl("child",id7).
decl("container",id2).
decl("mev",id5).
decl("mev",id6).
decl("mev",id8).
decl("step_children",id1).
pointerto(id2,"Container").
pointerto(id3,"Mevent").
pointerto(id4,"Part").
pointerto(id5,"Mevent").
pointerto(id6,"Mevent").
pointerto(id7,"Part").
pointerto(id8,"Mevent").
scope(id1,sc1).
scope(id2,sc2).
scope(id3,sc2).
scope(id4,sc3).
scope(id5,sc5).
scope(id6,sc6).
scope(id7,sc7).
scope(id8,sc9).
scopecontains(sc1,sc2).
scopecontains(sc2,sc3).
scopecontains(sc2,sc7).
scopecontains(sc3,sc4).
scopecontains(sc4,sc5).
scopecontains(sc5,sc6).
scopecontains(sc7,sc8).
scopecontains(sc7,sc9).
type(id1, procedure).
